spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentms?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.auggie.student_server.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 10086